# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9baa5e5b3423e13b6a100f5ca4f79fe108e84c2ebe0b5baed895e7da3e48645b80f0a6fac7e816f90aa4a832669999244bc4cd2db27add9e321bd8966592293d

test:
  secret_key_base: b15afa18fd27faee9629a3ed89c773bf7a8eb31d0c66d107d22aaa9a97b8f014e73b1313515d0240d10cf01ae85dba02a18a4cc8b36c7299e1e1835f64a1918e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
